version: '3'
services:
  opscale:
    container_name: opapi
    build: .
    ports:
    - "80:80"
    - "8081:8081"
    depends_on:
      - opmongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/client/node_modules
    networks:
      - oooonetwork
  opmongo:
    container_name: opmongo
    image: mongo
    restart: always
    ports:
    - "27017:27017"
    networks:
      - oooonetwork

networks:
  oooonetwork:
    driver: bridge
